### ISSUE TITLE
ADD EPM Predictions for not validated runs

### ISSUE THREAD

**Issue by mlindauer** [automl/SpySMAC#13]

**Comment by shukon** [comment]
@mlindauer do you it makes sense for me to implement this within the smac-validate utility of SMAC? adding an option for the smac-validate to use an EPM for validation instead of rerunning the tae? I feel like we talked about this a while ago.

**Comment by mlindauer** [comment]
I see that it could be less work for your to reuse the infrastructure of smac-validate.
However, I would prefer if SpySMAC would simply use the output folder of SMAC without any steps in-between. So, I would tend to answer your question with "No".

**Comment by shukon** [comment]
Well, I did not mean smac-validate. I meant smac/utils/validate.py, to add an EPM-option to the Validator (just to make clear what I mean). But anyway, I can do without.

**Comment by mlindauer** [comment]
That's fine if it lives in `smac/utils/validate.py` (if it makes things easier for you and not more complicated for users).
