### ISSUE TITLE
FIX example

### ISSUE THREAD

**Issue by mlindauer** [automl/SpySMAC#19]
`python ../../scripts/spy.py --folders example_output_run --output testing_output --verbose_level DEBUG` 

fails with the message

`FileNotFoundError: [Errno 2] No such file or directory: 'example_output_run/scenario.txt'`

**Comment by shukon** [comment]
You do have an `example_output_run` containing a scenario-file locally?
Still, that should not have happened, I updated the master-branch. May you please try again?

**Comment by mlindauer** [comment]
Based on the README, I would expect that `examples/spear_qcp_small` already provides `example_output_run`. Otherwise please provide instructions how to obtain `example_output_run`.

**Comment by shukon** [comment]
My bad! Did not update the README, updated the examples. Please try:
`python ../../scripts/spy.py --folders example_output_* --output testing_output` 
or `python ../../scripts/spy.py --folders example_output_1 --output testing_output` instead.
