### ISSUE TITLE
visualize configs

### ISSUE THREAD

**Issue by shukon** [automl/SpySMAC#21]
![conf_viz](https://user-images.githubusercontent.com/9417378/30446536-bfab5ec0-9989-11e7-8a94-4aed35818dd5.png)

**Comment by shukon** [comment]
Introduced in #30 
Open details: include incumbents, make design-choice

**Comment by mlindauer** [comment]
distinguish between random configs and model predicted configs

**Comment by mlindauer** [comment]
add tooltip
