### ISSUE TITLE
ADD coordinate plots

### ISSUE THREAD

**Issue by mlindauer** [automl/SpySMAC#41]

**Comment by shukon** [comment]
Plots added, a few bugs remain:
- sometimes not plotting the rightmost x-label
- scales should be adapted to int/float/categorical and unused parameters should be considered
- colours should reflect something - maybe performance of configuration?

**Comment by mlindauer** [comment]
> colours should reflect something - maybe performance of configuration?

yes, but use alpha values and not different colours.

only plot min(10, # params importance > 0.05)

**Comment by mlindauer** [comment]
looking again into the google visier paper, I figured out that they have a color range from blue (poorly performing configurations) to red (best performing configurations). Could be an alternative to the different alpha values.
