### ISSUE TITLE
Minor error in debug logoutput

### ISSUE THREAD

**Issue by AndreBiedenkapp** [automl/SpySMAC#45]
The order of the logged output seems to be wrong here:https://github.com/automl/SpySMAC/blob/682151477ede7a23f1e274dae2aa0e0b807ea13a/spysmac/spyfacade.py#L101-L104

Example output that threw me off:
> DEBUG:spysmac.spyfacade:Combined number of Runhistory data points: 1. # Configurations: 58242. # Runhistories: 29001

**Comment by shukon** [comment]
Certainly, thanks!
