### ISSUE TITLE
Algorithm-Footprints-instances overlap in scatterplot

### ISSUE THREAD

**Issue by shukon** [automl/SpySMAC#61]
When plotting good vs bad points, whatever is plotted first is completely hidden in parts of the instance space with high density. Solution might be plotting with alpha ([SO](https://stackoverflow.com/questions/19064772/visualization-of-scatter-plots-with-overlapping-points-in-matplotlib))

**Comment by mlindauer** [comment]
Please adjust alpha accordingly and please plot the bad points first---the good points are more important
