### ISSUE TITLE
Correlation Plot

### ISSUE THREAD

**Issue by shukon** [automl/SpySMAC#67]
I'm not sure needs to be fixed here... @mlindauer how do we want it to look?

**Comment by mlindauer** [comment]
The correlation plots are already included, right?

**Comment by shukon** [comment]
Yes, but they look overloaded. We might want to limit the plots to a certain number of features? Or is it more about the general resulting pattern?
![correlation_plot_features](https://user-images.githubusercontent.com/9417378/33559662-ccb91bfc-d90d-11e7-88dd-581b470324cd.png)

**Comment by mlindauer** [comment]
I think the issue was that the pattern in the old plots were very strange, i.e., a large fraction of the features were highly correlated. If it looks like the example above, this would be fine for me.

**Comment by shukon** [comment]
Perfect!
